### ISSUE TITLE
Invalid Slack invites return a non-error response

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#231]
You can test this out at https://hackclub.com/slack_invite/strategy_does_not_exist/1. The temporary email changes with every request.

**Comment by myrridin** [comment]
This is a pretty easy fix, but the test suite seems to have no tests for this area, and I'm unable to even run the test suite without what looks like a whole handful of API keys to setup. I hesitate to submit a PR without accompanying tests to verify the behavior. 

Do you have any suggestions on how to speed up the initial setup? Given that webmock/vcr appear to be in use, should this be modified so that the test suite can be run without any of the environment variables defined?
